# Generated by Django 4.2.7 on 2026-02-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('embeddings_count', models.IntegerField(default=0)),
                ('chat_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'API Usage',
            },
        ),
    ]
